@startuml
!include ./UI/RelicUIManager.puml
!include ./UI/SpellBarManager.puml
!include ./UI/ClassSelectorControl.puml
!include ./UI/RelicUI.puml
!include ./Combat/Hittable.puml
!include ./Combat/Damage.puml
!include ./Combat/HP.puml
!include ./AssetManagement/AssetManager.puml
!include ./AssetManagement/SpriteManager.puml
!include ./GameManager/GameManager.puml
!include ./ExecutionQueue/ExecutionQueue.puml
!include ./Spells/SpellReader.puml
!include ./Spells/Spell.puml
!include ./Spells/SpellModifier.puml
!include ./Spells/SpellBuilder.puml
!include ./Spells/Projectile.puml
!include ./Events/EventBus.puml
!include ./Levels/WaveManager.puml
!include ./Levels/WaveStats.puml
!include ./UI/UIState/UIState.puml
!include ./UI/UIDispatcher/UIDispatcher.puml
!include ./UI/UIScreens/DifficultySelectButton.puml
!include ./UI/UIScreens/Win.puml
!include ./UI/UIScreens/DifficultySelect.puml
!include ./UI/UIScreens/Death.puml
!include ./UI/UIScreens/Reward.puml
!include ./UI/UIScreens/GiveSpellReward.puml
!include ./UI/UIElements/ManaBar.puml
!include ./UI/UIElements/WaveLabelController.puml
!include ./UI/UIElements/DamageNumbers.puml
!include ./UI/UIElements/AnimateDamage.puml
!include ./Combat/Teams/Teams.puml
!include ./Combat/AttackRadius/AttackRadius.puml
!include ./Levels/SpawnPoint/SpawnPoint.puml
!include ./Levels/Level/Level.puml
!include ./Enemies/EnemyStatData/EnemyStatData.puml
!include ./Enemies/EnemySpawner/EnemySpawner.puml
!include ./Enemies/BatchSpawnData/BatchSpawnData.puml
!include ./Enemies/EnemyInstance/EnemyInstance.puml
!include ./Player/PlayerClassData/PlayerClassData.puml
!include ./Player/PlayerClassManager/PlayerClassManager.puml
!include ./Player/PlayerInstance/PlayerInstance.puml
!include ./UI/UIScreens/UIScreen/UIScreen.puml
!include ./UI/UIElements/HealthBar/HealthBar.puml
@enduml
